### ISSUE TITLE
测试时报错 oracle版本11g 和mysql5.7

### ISSUE THREAD

**Issue by lutao043** [iverycd/oracle_to_mysql#8]
>oracle_mig_mysql -q -p 4
2023-06-15 17:50:58.638739 run begin tool defaultencoding-> utf-8  sys.stdin.encoding-> utf-8 sys.stdout.encoding-> utf-8
+--------------------------------------------------------+
| Oracle Migrate MySQL Tool                              |
+--------------------------------------------------------+
| MySQL 5.7 and Oracle 11g higher Support                |
| Powered By DBA Group of Infrastructure Research Center |
| Version v1.23.4.10                                     |
+--------------------------------------------------------+

Source Database information:
+----------+-------------+----------------------------------------------------------------+
| database | schema_info |                          connect_info                          |
+----------+-------------+----------------------------------------------------------------+
| ****|   ***| ((HOST=*****)(PORT=4750))((SERVICE_NAME=helowinXDB))) |
+----------+-------------+----------------------------------------------------------------+
+------------------------------+
| migrate mode                 |
+------------------------------+
| Migration Mode:full database |
+------------------------------+
Source Database Information:
+--------+-------+----------+------------+-----------+----------+
| tables | views | triggers | procedures | functions | packages |
+--------+-------+----------+------------+-----------+----------+
| 1042   |   0   |    0     |     5      |     7     |    0     |
+--------+-------+----------+------------+-----------+----------+

Target Database Information:
+----------+-----------+----------+-----------+---------+
| database |  ip_addr  | port_num | user_name | db_name |
+----------+-----------+----------+-----------+---------+
| MySQL    | 127.0.0.1 |   3306   |    root   | BIZHALL |
+----------+-----------+----------+-----------+---------+
2023-06-15 17:51:03
QUITE MODE
GO
Traceback (most recent call last):
  File "oracle_mig_mysql.py", line 669, in <module>
  File "oracle_mig_mysql.py", line 623, in main
  File "db_info.py", line 745, in cte_tab
  File "dbutils\steady_db.py", line 598, in tough_method
  File "pymysql\cursors.py", line 148, in execute
  File "pymysql\cursors.py", line 310, in _query
  File "pymysql\connections.py", line 548, in query
  File "pymysql\connections.py", line 775, in _read_query_result
  File "pymysql\connections.py", line 1156, in read
  File "pymysql\connections.py", line 725, in _read_packet
  File "pymysql\protocol.py", line 221, in raise_for_error
  File "pymysql\err.py", line 143, in raise_mysql_exception
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1' at line 1")
[20240] Failed to execute script oracle_mig_mysql

**Comment by lutao043** [comment]
程序版本为v1.23.4.10-Windows

**Comment by iverycd** [comment]
bug已修复请使用新版本https://github.com/iverycd/oracle_to_mysql/releases/tag/v1.4.1
